CREATE TABLE keys(
  _master VARCHAR (56) NOT NULL,
  _app VARCHAR (56) NOT NULL,
  _user VARCHAR (56) NOT NULL,
  _key VARCHAR (56) PRIMARY KEY UNIQUE NOT NULL,
  passkey VARCHAR UNIQUE NOT NULL,
  cipher VARCHAR UNIQUE NOT NULL,
  name VARCHAR (140) DEFAULT NULL,
  image VARCHAR (140) DEFAULT NULL,
  link VARCHAR (140) DEFAULT NULL,
  claimedat BIGINT DEFAULT (extract(epoch from now()) * 1000) NOT NULL,
  verifiedat BIGINT DEFAULT NULL
);